// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxZCpE0aSRFvYIiHvmEx3oD8uLyZWSKpU',
    appId: '1:508112603482:web:624d70c724fa7e5f1b0b63',
    messagingSenderId: '508112603482',
    projectId: 'food-delivery-app-1f284',
    authDomain: 'food-delivery-app-1f284.firebaseapp.com',
    storageBucket: 'food-delivery-app-1f284.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRi4_uF0gaAOUroe4QcUcRvGmpCjVJ2aQ',
    appId: '1:508112603482:android:22fd6d61aa6549f01b0b63',
    messagingSenderId: '508112603482',
    projectId: 'food-delivery-app-1f284',
    storageBucket: 'food-delivery-app-1f284.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH4_-qiJSRiY2DK2Jq2LL1Lc2WTw8t6lk',
    appId: '1:508112603482:ios:68385e717f09c9421b0b63',
    messagingSenderId: '508112603482',
    projectId: 'food-delivery-app-1f284',
    storageBucket: 'food-delivery-app-1f284.firebasestorage.app',
    iosBundleId: 'com.pradhyumnsingh.foodDeliveryApp',
  );
}
